---

  - name: "copy backend binaries"
    copy:
      src: backend.tar.gz
      dest: /home/ubuntu/backend.tar.gz

  - name: Start PM2
    shell: |
      cd /home/ubuntu/
      tar xzvf backend.tar.gz
      cd backend
      sudo npm install 
      pm2 stop default
      pm2 start npm -- start